### Çoklu Doğrusal Regresyonda Tahmin İşlemleri

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x: '%.2f' % x)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score

df = pd.read_csv('datasets/advertising.csv')
df

TV  radio  newspaper  sales
0   230.10  37.80      69.20  22.10
1    44.50  39.30      45.10  10.40
2    17.20  45.90      69.30   9.30
3   151.50  41.30      58.50  18.50
4   180.80  10.80      58.40  12.90
..     ...    ...        ...    ...
195  38.20   3.70      13.80   7.60
196  94.20   4.90       8.10   9.70
197 177.00   9.30       6.40  12.80
198 283.60  42.00      66.20  25.50
199 232.10   8.60       8.70  13.40

[200 rows x 4 columns]

In [3]:
# Bağımsız değişkenlerin seçimi:
x = df.drop('sales', axis=1)

# Bağımlı değişken seçimi:
y = df[["sales"]]

###### Model

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

In [5]:
reg_model = LinearRegression().fit(x_train, y_train)

In [6]:
# sabit (b - bias)
reg_model.intercept_

array([2.90794702])

In [7]:
# coefficients (w - weights)
reg_model.coef_

array([[0.0468431 , 0.17854434, 0.00258619]])

### Tahmin

* Aşağıdaki gözlem değerlerine göre satışın beklenen değeri nedir?
* TV : 30
* radio : 10
* newspaper : 40

* sabit : 2.90
* ağırlıklar : 0.0468431 , 0.17854434, 0.00258619

###### Model denklemini yazınız. (Mülakatta sorulur...)

In [8]:
# Sales = 2.90794702 + TV *  0.0468431 + radio * 0.17854434 + newspaper * 0.00258619

###### Tahmin edilen satışı yukarıdaki model denklemine göre verilen gözlem değerleri ile bulunuz.

In [13]:
2.90794702 + 30 * 0.0468431 + 10 * 0.17854434 + 40 * 0.00258619

6.20213102

In [11]:
# Bu ifadeyi fonksiyonel şekilde yazmak için:

# Liste oluşturalım:
yeni_veri = [[30], [10], [40]]

# Bunu bir dataframe'e çevirelim:
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [12]:
# Model nesnemizi getiriyoruz ve tahmin et diyoruz. Ancak neyi tahmin edeceğiz? Bize bağımsız değişkenleri ver biz gidelim 
# regresyon modeline bunları soralım. Buna göre de bağımlı değişkenin ne olabileceği bilgisini sana getireyim.
reg_model.predict(yeni_veri)

C:\Users\aleyy\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.202131]])